title: <p align="center"> Srujana </p>
logo: /assets/img/logo1.png
description: <p align="center">
             <a href="pdf/resume.pdf">Resume</a>
             <a href="https://www.linkedin.com/in/srujana-nandam-41b84318/">LinkedIn</a>
             <a href="https://github.com/nsrujana">Github</a>
             <br>
             Woring on Developing Sustainable Materials,Vibrations and Dynamics of Structures 
             <br>
</p>

